# 循环神经网络

尝试使用`Numpy`手搓最简单的RNN实现

## 准备数据

目标是用'hello'这个单词训练，希望能得到的是输入'hell',推理出'o'

'hello'作为一个序列，每个字母是序列的元素，进行one-hot encoding, 这里太简单所以直接手动指定

In [1]:
import numpy as np

h = np.array([1,0,0,0])
e = np.array([0,1,0,0])
l = np.array([0,0,1,0])
o = np.array([0,0,0,1])

print(h)
print(e)
print(l)
print(o)

[1 0 0 0]
[0 1 0 0]
[0 0 1 0]
[0 0 0 1]
