# 循环神经网络

尝试使用`Numpy`手搓最简单的RNN实现

## 准备数据

目标是用'hello'这个单词训练，希望能得到的是输入'hell',推理出'o'

'hello'作为一个序列，每个字母是序列的元素，进行one-hot encoding, 这里太简单所以直接手动指定

In [1]:
import numpy as np

h = np.array([1,0,0,0])
e = np.array([0,1,0,0])
l = np.array([0,0,1,0])
o = np.array([0,0,0,1])

print(h)
print(e)
print(l)
print(o)

[1 0 0 0]
[0 1 0 0]
[0 0 1 0]
[0 0 0 1]


假设循环神经网络的hidden size是100,那么定义$W_{xh}$和$W_{hh}$

In [2]:
Wxh = np.random.randn(100,4)*0.01
Whh = np.random.randn(100,100)*0.01

print(Wxh)
print(Whh)

[[-1.36252251e-02 -1.25801255e-02  7.24461571e-03 -1.43573197e-02]
 [ 1.15780506e-02 -8.25122140e-04  1.74090420e-03 -7.46117853e-03]
 [-1.50895013e-02 -3.40339871e-03  1.57505595e-04 -1.36583070e-02]
 [ 3.64211158e-03 -1.00508475e-02  1.09444611e-02  1.67669551e-02]
 [-3.38713973e-03 -9.32646114e-03  5.87976393e-03 -6.53131924e-03]
 [ 2.28914503e-03 -3.68772863e-03 -2.75527959e-03  1.96093201e-02]
 [-1.25186906e-02 -3.12791950e-03  9.51912278e-03 -6.39406581e-03]
 [ 2.32721913e-03  3.99234096e-03  1.89535462e-03  9.88985532e-04]
 [-1.32430379e-02 -3.48640437e-04  4.59654385e-03  1.36493301e-02]
 [-1.22966821e-02 -5.23979186e-03  9.04595817e-03  1.30097802e-02]
 [-5.61142772e-03  2.73909375e-02  1.96330376e-02 -1.13022179e-02]
 [ 7.80885532e-03 -1.86501779e-02  2.96683498e-03  3.16435532e-03]
 [ 1.62353647e-02  1.67514875e-03  7.89724555e-03 -1.02096517e-02]
 [-1.92438638e-04 -1.45579580e-03  1.78525791e-02  7.89075833e-03]
 [ 1.76767937e-03  3.79149766e-03  2.77060406e-03 -2.01564446e

定义输出的权重


In [3]:
Why = np.random.randn(4,100)*0.01
print(Why)

[[-1.33519711e-02  1.38571655e-02 -6.42611369e-06  2.12345204e-03
  -4.48765108e-03 -1.65025336e-02 -1.23144313e-03 -1.69189250e-03
  -2.02279260e-02 -1.07303772e-02 -1.69019608e-02  1.66353129e-02
  -5.75031294e-03 -8.10408910e-03 -1.05962243e-02 -1.28185893e-02
   1.14419532e-02  2.85706450e-03 -3.19228875e-02 -1.72218591e-03
   6.53316269e-03 -1.10811112e-02  1.72740062e-03  8.50015464e-03
  -1.60258659e-03  1.07292747e-02  2.27770913e-02  2.80435771e-03
  -1.47456374e-02  1.01653601e-02 -3.82505498e-03  6.75442150e-03
  -4.21481860e-03  5.50224246e-03  8.72180589e-03  1.18370006e-02
  -1.61282042e-03  7.46589696e-03 -1.77360464e-02  9.97005273e-03
   5.98530418e-04 -3.59313153e-03  1.97535936e-02  1.98059584e-02
   6.99017703e-03  5.28049092e-03  1.10805497e-02 -5.45222452e-04
  -6.71261083e-03 -2.06513556e-02 -1.35933399e-02 -1.51170206e-02
  -6.10954789e-03  3.11924141e-04  1.95134143e-03 -1.30922863e-02
  -5.91162763e-04 -3.87141681e-03  3.38675690e-03  2.23216459e-02
   2.68028