# 向量和矩阵的操作

## 向量和矩阵的乘法

先贴一个GPT4的回答
>在矩阵和向量的乘法中，通常情况下，我们考虑的是一个矩阵乘以一个列向量的操作。这种乘法遵循线性代数中的矩阵乘法规则，要求矩阵的列数与向量的行数（元素数量）相匹配。

>如果A是一个m×n的矩阵（m行n列），x是一个n维列向量（n×1），那么乘法Ax是可能的，其结果是一个m维列向量。这种乘法在很多应用中非常常见，例如线性变换、线性系统的求解等。

>然而，向量也可以先转置成行向量（一个1×n的矩阵），然后乘以一个矩阵。在这种情况下，假设x是一个n维行向量（1×n），而A是一个n×m的矩阵，那么x乘以A（记作xA）也是可能的，其结果将是一个1×m的行向量。

>总结一下，矩阵和向量的乘法遵循以下规则：

>一个矩阵（m×n）乘以一个列向量（n×1）得到一个列向量（m×1）。
>一个行向量（1×n）乘以一个矩阵（n×m）得到一个行向量（1×m）。
>在这两种情况下，关键是内部的维度（矩阵的列数和向量的行数）必须相匹配。如果维度不匹配，那么乘法是不允许的。

In [1]:
import numpy as np

A = np.array([[1,2],[3,4]])

print(A)

[[1 2]
 [3 4]]


In [2]:
v = np.array([5,6]) #数组

result = A.dot(v)

print(result)

[17 39]


In [3]:
result1 = A @ v
print(result1)

[17 39]


In [4]:
result2 = v.dot(A)
print(result2)

[23 34]


上面的操作可以看出来，用np的数组，在运算中决定了是行向量还是列向量

计算result、result1的时候，是矩阵乘以向量，那么数组就是列向量
计算result2的时候，是向量乘以矩阵，是行向量乘以矩阵，那么数组是行向量

GPT提醒
>需要注意的是，当你使用dot或@运算符来进行矩阵与向量的乘法时，输出结果的形状将取决于输入数组的形状。如果输入的向量是一个一维数组，输出结果将是一个一维数组；如果输入的向量是一个二维列向量（n×1形状），输出结果将是一个二维数组（m×1形状）。

In [5]:
v1 = np.array([[5],[6]]) #列向量，二维数组形式
result3 = A @ v1
print(result3)

[[17]
 [39]]


In [6]:
v2 = np.array([[5,6]]) # 行向量，二维数组形式
result4 = v2 @ A
print(result4)

[[23 34]]


根据以上代码，验证完毕